package com.edusasse.sample.calc.server;


/**
* calculadora/_calc_numericaStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Segunda-feira, 18 de Maio de 2009 15h36min02s BRT
*/

public class _calc_numericaStub extends org.omg.CORBA.portable.ObjectImpl implements com.edusasse.sample.calc.server.calc_numerica
{

  public boolean soma_int (short p1, short p2, org.omg.CORBA.ShortHolder ret)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("soma_int", true);
                $out.write_short (p1);
                $out.write_short (p2);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                ret.value = $in.read_short ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return soma_int (p1, p2, ret        );
            } finally {
                _releaseReply ($in);
            }
  } // soma_int

  public boolean sub_int (short p1, short p2, org.omg.CORBA.ShortHolder ret)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("sub_int", true);
                $out.write_short (p1);
                $out.write_short (p2);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                ret.value = $in.read_short ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return sub_int (p1, p2, ret        );
            } finally {
                _releaseReply ($in);
            }
  } // sub_int

  public boolean div_double (double p1, double p2, org.omg.CORBA.ShortHolder ret)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("div_double", true);
                $out.write_double (p1);
                $out.write_double (p2);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                ret.value = $in.read_short ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return div_double (p1, p2, ret        );
            } finally {
                _releaseReply ($in);
            }
  } // div_double

  public boolean mul_double (double p1, double p2, org.omg.CORBA.ShortHolder ret)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("mul_double", true);
                $out.write_double (p1);
                $out.write_double (p2);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                ret.value = $in.read_short ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return mul_double (p1, p2, ret        );
            } finally {
                _releaseReply ($in);
            }
  } // mul_double

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:calculadora/calc_numerica:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.Object obj = org.omg.CORBA.ORB.init (args, props).string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     String str = org.omg.CORBA.ORB.init (args, props).object_to_string (this);
     s.writeUTF (str);
  }
} // class _calc_numericaStub
