package com.edusasse.sample.calc.server;


/**
* calculadora/calc_numericaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Segunda-feira, 18 de Maio de 2009 15h36min02s BRT
*/

public interface calc_numericaOperations 
{
  boolean soma_int (short p1, short p2, org.omg.CORBA.ShortHolder ret);
  boolean sub_int (short p1, short p2, org.omg.CORBA.ShortHolder ret);
  boolean div_double (double p1, double p2, org.omg.CORBA.ShortHolder ret);
  boolean mul_double (double p1, double p2, org.omg.CORBA.ShortHolder ret);
} // interface calc_numericaOperations
