package com.edusasse.sample.calc.server;


/**
* calculadora/calc_alfaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Segunda-feira, 18 de Maio de 2009 15h36min02s BRT
*/

public interface calc_alfaOperations 
{
  String soma_str (String str1, String str2);
  String mistura_str (String str1, String str2);
} // interface calc_alfaOperations
