package com.edusasse.sample.calc.server;


/**
* calculadora/calc_alfaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Segunda-feira, 18 de Maio de 2009 15h36min02s BRT
*/

abstract public class calc_alfaHelper
{
  private static String  _id = "IDL:calculadora/calc_alfa:1.0";

  public static void insert (org.omg.CORBA.Any a, com.edusasse.sample.calc.server.calc_alfa that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.edusasse.sample.calc.server.calc_alfa extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.edusasse.sample.calc.server.calc_alfaHelper.id (), "calc_alfa");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.edusasse.sample.calc.server.calc_alfa read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_calc_alfaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.edusasse.sample.calc.server.calc_alfa value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.edusasse.sample.calc.server.calc_alfa narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.edusasse.sample.calc.server.calc_alfa)
      return (com.edusasse.sample.calc.server.calc_alfa)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.edusasse.sample.calc.server._calc_alfaStub stub = new com.edusasse.sample.calc.server._calc_alfaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static com.edusasse.sample.calc.server.calc_alfa unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.edusasse.sample.calc.server.calc_alfa)
      return (com.edusasse.sample.calc.server.calc_alfa)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.edusasse.sample.calc.server._calc_alfaStub stub = new com.edusasse.sample.calc.server._calc_alfaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
