package com.edusasse.sample.calc.server;


/**
* calculadora/calc_numerica.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Segunda-feira, 18 de Maio de 2009 15h36min02s BRT
*/

public interface calc_numerica extends calc_numericaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface calc_numerica
