package com.edusasse.sample.calc.server;

/**
* calculadora/calc_numericaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Segunda-feira, 18 de Maio de 2009 15h36min02s BRT
*/

public final class calc_numericaHolder implements org.omg.CORBA.portable.Streamable
{
  public com.edusasse.sample.calc.server.calc_numerica value = null;

  public calc_numericaHolder ()
  {
  }

  public calc_numericaHolder (com.edusasse.sample.calc.server.calc_numerica initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.edusasse.sample.calc.server.calc_numericaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.edusasse.sample.calc.server.calc_numericaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.edusasse.sample.calc.server.calc_numericaHelper.type ();
  }

}
