package com.edusasse.sample.calc.server;


/**
* calculadora/calc_numericaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Calculadora.idl
* Segunda-feira, 18 de Maio de 2009 15h36min02s BRT
*/

public abstract class calc_numericaPOA extends org.omg.PortableServer.Servant
 implements com.edusasse.sample.calc.server.calc_numericaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("soma_int", new java.lang.Integer (0));
    _methods.put ("sub_int", new java.lang.Integer (1));
    _methods.put ("div_double", new java.lang.Integer (2));
    _methods.put ("mul_double", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // calculadora/calc_numerica/soma_int
       {
         short p1 = in.read_short ();
         short p2 = in.read_short ();
         org.omg.CORBA.ShortHolder ret = new org.omg.CORBA.ShortHolder ();
         boolean $result = false;
         $result = this.soma_int (p1, p2, ret);
         out = $rh.createReply();
         out.write_boolean ($result);
         out.write_short (ret.value);
         break;
       }

       case 1:  // calculadora/calc_numerica/sub_int
       {
         short p1 = in.read_short ();
         short p2 = in.read_short ();
         org.omg.CORBA.ShortHolder ret = new org.omg.CORBA.ShortHolder ();
         boolean $result = false;
         $result = this.sub_int (p1, p2, ret);
         out = $rh.createReply();
         out.write_boolean ($result);
         out.write_short (ret.value);
         break;
       }

       case 2:  // calculadora/calc_numerica/div_double
       {
         double p1 = in.read_double ();
         double p2 = in.read_double ();
         org.omg.CORBA.ShortHolder ret = new org.omg.CORBA.ShortHolder ();
         boolean $result = false;
         $result = this.div_double (p1, p2, ret);
         out = $rh.createReply();
         out.write_boolean ($result);
         out.write_short (ret.value);
         break;
       }

       case 3:  // calculadora/calc_numerica/mul_double
       {
         double p1 = in.read_double ();
         double p2 = in.read_double ();
         org.omg.CORBA.ShortHolder ret = new org.omg.CORBA.ShortHolder ();
         boolean $result = false;
         $result = this.mul_double (p1, p2, ret);
         out = $rh.createReply();
         out.write_boolean ($result);
         out.write_short (ret.value);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:calculadora/calc_numerica:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public calc_numerica _this() 
  {
    return calc_numericaHelper.narrow(
    super._this_object());
  }

  public calc_numerica _this(org.omg.CORBA.ORB orb) 
  {
    return calc_numericaHelper.narrow(
    super._this_object(orb));
  }


} // class calc_numericaPOA
