package com.edusasse.jwalla.server.corba;

/**
* com/edusasse/jwalla/server/Corba/ServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Terça-feira, 3 de Março de 2009 15h40min13s BRT
*/

public final class ServerHolder implements org.omg.CORBA.portable.Streamable
{
  public com.edusasse.jwalla.server.corba.Server value = null;

  public ServerHolder ()
  {
  }

  public ServerHolder (com.edusasse.jwalla.server.corba.Server initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = com.edusasse.jwalla.server.corba.ServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    com.edusasse.jwalla.server.corba.ServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return com.edusasse.jwalla.server.corba.ServerHelper.type ();
  }

}
