package com.edusasse.jwalla.server.corba;


/**
* com/edusasse/jwalla/server/Corba/ServerPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Terça-feira, 3 de Março de 2009 15h40min13s BRT
*/

public abstract class ServerPOA extends org.omg.PortableServer.Servant
 implements com.edusasse.jwalla.server.corba.ServerOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("callServerUpdate", new java.lang.Integer (0));
    _methods.put ("getServiceName", new java.lang.Integer (1));
    _methods.put ("instanceSync", new java.lang.Integer (2));
    _methods.put ("update", new java.lang.Integer (3));
    _methods.put ("createRemoteClientConnection", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // com/edusasse/jwalla/server/Corba/Server/callServerUpdate
       {
         int id = in.read_long ();
         String XMLComands = in.read_string ();
         String $result = null;
         $result = this.callServerUpdate (id, XMLComands);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // com/edusasse/jwalla/server/Corba/Server/getServiceName
       {
         String $result = null;
         $result = this.getServiceName ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // com/edusasse/jwalla/server/Corba/Server/instanceSync
       {
         String $result = null;
         $result = this.instanceSync ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // com/edusasse/jwalla/server/Corba/Server/update
       {
         String XMLComands = in.read_string ();
         boolean $result = false;
         $result = this.update (XMLComands);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // com/edusasse/jwalla/server/Corba/Server/createRemoteClientConnection
       {
         String xml = in.read_string ();
         String $result = null;
         $result = this.createRemoteClientConnection (xml);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:com/edusasse/jwalla/server/Corba/Server:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Server _this() 
  {
    return ServerHelper.narrow(
    super._this_object());
  }

  public Server _this(org.omg.CORBA.ORB orb) 
  {
    return ServerHelper.narrow(
    super._this_object(orb));
  }


} // class ServerPOA
