package com.edusasse.jwalla.server.corba;


/**
* com/edusasse/jwalla/server/Corba/ServerHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Terça-feira, 3 de Março de 2009 15h40min13s BRT
*/

abstract public class ServerHelper
{
  private static String  _id = "IDL:com/edusasse/jwalla/server/Corba/Server:1.0";

  public static void insert (org.omg.CORBA.Any a, com.edusasse.jwalla.server.corba.Server that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static com.edusasse.jwalla.server.corba.Server extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (com.edusasse.jwalla.server.corba.ServerHelper.id (), "Server");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static com.edusasse.jwalla.server.corba.Server read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ServerStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, com.edusasse.jwalla.server.corba.Server value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static com.edusasse.jwalla.server.corba.Server narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.edusasse.jwalla.server.corba.Server)
      return (com.edusasse.jwalla.server.corba.Server)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.edusasse.jwalla.server.corba._ServerStub stub = new com.edusasse.jwalla.server.corba._ServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static com.edusasse.jwalla.server.corba.Server unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof com.edusasse.jwalla.server.corba.Server)
      return (com.edusasse.jwalla.server.corba.Server)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      com.edusasse.jwalla.server.corba._ServerStub stub = new com.edusasse.jwalla.server.corba._ServerStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
