package com.edusasse.jwalla.server.corba;

import com.edusasse.jwalla.server.i_Server;


/**
* com/edusasse/jwalla/server/Corba/Server.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Server.idl
* Terça-feira, 3 de Março de 2009 15h40min13s BRT
*/

public interface Server extends ServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity , i_Server
{
} // interface Server
